### PR TITLE
Break out of potentially infinite rescaling loop after 1000 iterations

### PR DESCRIPTION
**Pull request by martin-frbg**
inf values in the input vector will survive rescaling, making the code hang. The limit of 1000 iterations is arbitrarily chosen with the intention to never interfere with regular behaviour. Fixes issue #196

### CODE REVIEW

**Comment by langou** [comment]
Thanks Martin. I will review some more. 

Another way to go is to check for infinity in BETA. I wonder if we cannot use the intrinsic ieee_is_finite(). I wonder how widely the intrinsic ieee_is_finite() is supported by compilers. This is part of Fortran 2003 standard. We do not use this intrinsic in LAPACK yet. To check for infinity, we could also check whether ABS( BETA ) is larger than the largest finite number or not.

Three questions in my mind. (1) What behavior do we want for LARFG if BETA is INF? (2) Does the code with (KNT .LT. 1000) behaves as the behavior in (1)? ( I think so. ) (3) Do we want 1000? Sounds like 20 is enough.

For sure if BETA is INF, we have an infinite loop and your fix removes this infinite loop. So this is great.

So, thanks a lot for the pull request. 

I will also try to update and change 
+            IF( ABS( BETA ).LT.SAFMIN .AND. KNT .LT. 1000)
with
+            IF( ( ABS( BETA ).LT.SAFMIN ) .AND. ( KNT.LT.1000) )
(so with parenthesis, this is more LAPACK notation like, really no big deal.)
I will need to learn how to edit a pull request. I'll see for this. 

Great. Thanks. 
Julien.

**Comment by martin-frbg** [comment]
I can update the pull request with added parentheses if you like (I am not sure if I would know how to edit someone else's pull request either), but feel free to ignore this altogether if you have a more elegant solution (or rather, an elegant solution at all - I am quite aware that mine is just a dirty hack to make things work). 
I had a quick look around the internet and I think the issue with the ieee intrinsic was that some older version of gfortran did not support it. Not sure if this would be a concern here (and I do not recall the version number anyway, probably something relatively ancient like 4.3).

**Comment by langou** [comment]
Let us accept this pull request for the coming release and revisit the issue later. 
I am merging the PR and creating an issue.

**Comment by martin-frbg** [comment]
Thanks for merging this despite its obvious shortcomings. Issue #204 is sort-of a duplicate of my #196 now I think ?

**Comment by langou** [comment]
Indeed. I thought the merge of your fix would close the issue, and so I opened a new issue. Indeed there is no point in this. Thanks for pointing this out. Closing #204.

**Comment by vladimir-ch** [comment]
Sorry for commenting on a merged PR but I've been wondering whether this change actually does anything if `X` contains infinite values.

If `X` contains infinities, then `XNORM` will be infinite, `DLAPY2( ALPHA, XNORM )` will be infinite, and so `BETA` will be infinite. Finally, `ABS( BETA ).LT.SAFMIN` will be false and the branch with the loop will not be executed. Am I missing anything?

**Comment by vladimir-ch** [comment]
On the other hand, if `X` contains infinities, `TAU` will be NaN, which is what may have been causing the issue in the original OpenBLAS ticket.

**Comment by martin-frbg** [comment]
This issue was meant to be revisited, which is why #196 was kept open. My fix was certainly not elegant and probably not all-encompassing, but I was not sure how to (reliably, portably) check for INF and "the loop was there", so limiting its counter was trivial. Checking TAU for NaN looks like the clever thing to do, but at least currently it is calculated only after the problematic loop so would not help. (Whatever ABS(BETA) was at that point, it did appear to be .LT.SAFMIN in practice, though maybe it was actually NaN and the comparison was undefined)

**Comment by vladimir-ch** [comment]
Sorry, I should have better commented on #196. I will take the discussion there.

**Pull request merged**
