### PR TITLE
use integer64 flag for Cray Fortran compiler

### PR DESCRIPTION
**Pull request by ajaypanyala**
**Description**
  use `default64` flag for Cray ftn compiler when BUILD_INDEX64 is ON.

**Checklist**

- [ X] The documentation has been updated.
- [X ] If the PR solves a specific issue, it is set to be closed on merge.

### CODE REVIEW

**Review by langou — DISMISSED** [review]

**Comment by ajaypanyala** [comment]
@langou Could you please review the latest commit again, thanks!

**Comment by weslleyspereira** [comment]
Hi @ajaypanyala. Could you please help resolving this conflict?
We accepted #624 that uses `set(FORTRAN_ILP TRUE)` instead of `set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fdefault-integer-8")`. I am not sure if #624 is sufficient to enable `default64` flag for Cray ftn compiler.

**Comment by ajaypanyala** [comment]
Hi @weslleyspereira I can update #617 to reflect my comment on #624. Please let me know If you want me to proceed with that.

**Comment by weslleyspereira** [comment]
> Hi @weslleyspereira I can update #617 to reflect my comment on #624. Please let me know If you want me to proceed with that.

Oh, now I see the command `set(CMAKE_Fortran_FLAGS ... )` was only moved (and not removed) in #617. I agree with your proposed changes. You can proceed with the modifications. Thanks!

**Review by weslleyspereira — APPROVED** [review]

**Pull request merged**
