### PR TITLE
 Use cmake builtin tool for "env" to ensure cross-platform compatibility 

### LINKED ISSUE #530: Turn on BLAS++, blaspp build error.
Turn on BLAS++, blaspp build error:
FAILED: blaspp-prefix/src/blaspp-stamp/blaspp-configure

Trun off BLAS++, lapackpp also build error:
FAILED: lapackpp-prefix/src/lapackpp-stamp/lapackpp-configure

WIN10X64+ifort.exe

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #530

### CODE REVIEW

**Comment by weslleyspereira** [comment]
Thanks, @martin-frbg. Should we turn on BLASPP and LAPACKPP on the CI tools?

**Review by weslleyspereira — APPROVED** [review]

**Comment by martin-frbg** [comment]
I don't really know - both would do a download from Mark Gates' bitbucket site,  which could cause spurious failures in case of network problems

**Comment by weslleyspereira** [comment]
Hm... I see. In that case, I think it may not be a good idea.

**Comment by h-vetinari** [comment]
The CI here doesn't run crazy often; even if a network issue appear, it can be restarted. I'd say better to test things that are expected to work with slight attendant inconvenience, than not at all.

**Pull request merged**
