### PR TITLE
NaN not propagating in DCOMBSSQ and SCOMBSSQ

### PR DESCRIPTION
**Pull request by pdalgd**
S/DCOMBSSQ do not propagate NaN  in some cases. The problem case is V1(1)=V2(1)=0 with V2(2)=NaN.  Without the fix (the inner ELSE), control passes through without ever looking at V2(2). This was discovered in R (www.r-project.org), where a Frobenius norm (DLANGE) of the matrix

0 NA  0
0  0 -1

returns 1 with LAPACK 3.9.0 but gave NA with earlier versions.

### CODE REVIEW

**Comment by julielangou** [comment]
Thanks!

**Comment by martin-frbg** [comment]
As a side effect this added a spurious .DS_Store file to the base directory  (some kind of directory attribute storage on OSX apparently)

**Comment by langou** [comment]
Fixed with 0b0622702845c65f898f1cb9359a3aa167bf7ef3

**Comment by pdalgd** [comment]
Sorry about that, please remove. I blame my lacking github expertise. (Yes, MacOS creates those files all over the place.)

-pd

> On 23 Feb 2020, at 17:33 , Martin Kroeker <notifications@github.com> wrote:
> 
> As a side effect this added a spurious .DS_Store file to the base directory (some kind of directory attribute storage on OSX apparently)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Peter Dalgaard, Professor,
Center for Statistics, Copenhagen Business School
Solbjerg Plads 3, 2000 Frederiksberg, Denmark
Phone: (+45)38153501
Office: A 4.23
Email: pd.mes@cbs.dk  Priv: PDalgd@gmail.com

**Pull request merged**
