### PR TITLE
Reinserted frecursive due to prior bug-reports

### PR DESCRIPTION
**Pull request by zerothi**
See 3a87b2df45b999b6da5a4ee3f54c766c7b1e8f4d for details.

Also, see comment by @pv in #177.

### CODE REVIEW

**Comment by langou** [comment]
Super. Thanks. I should not have accepted the initial pull-request in the first place. Thanks for the second pull request. I am letting Travis CI do its job and then I will process the merge. Cheers, Julien.

**Comment by zerothi** [comment]
No, I should have noticed. Sorry for the mistake.

**Comment by zerothi** [comment]
@langou it fails on MacOSX, but the errors seem un-related?

**Comment by julielangou** [comment]
ok, Yes indeed. Thanks

**Pull request merged**
