### PR TITLE
Uses Valgrind for ExperimentalMemCheck in ctest

### PR DESCRIPTION
**Pull request by weslleyspereira**
Uses valgrind if it is available.

TO-DO
- [x] Try to optimize the runs with Valgrind. The test is currently taking too much time to complete.

### CODE REVIEW

**Comment by weslleyspereira** [comment]
Related to https://github.com/Reference-LAPACK/lapack/pull/551#issuecomment-1568701639

**Comment by weslleyspereira** [comment]
I believe this is also related to #790.

**Comment by weslleyspereira** [comment]
Related to #911 and #790.

**Review by langou — DISMISSED** [review]

**Comment by langou** [comment]
Wow! That's amazing. Thanks @weslleyspereira !

**Comment by weslleyspereira** [comment]
It should be ready for merge.

There are some spurious defects found in by Valgrind only when used in the Github CI. I am not sure where they come from.

1. no information is provided in the MemoryCheck files.
2. I can't reproduce it locally.

So, I opt for ignoring those defects in the CI for now.

**Pull request merged**
