### PR TITLE
Remove legacy function LABAD

### PR DESCRIPTION
**Pull request by angsch**
**Description**

LABAD is a legacy function that used to make LAPACK usable on machines that did not comply with IEEE arithmetic. This PR removes the function calls to LABAD and turns LABAD itself into a no-op. See also #96.

If you agree that the removal (rather than turning the routine only into a no-op) is the right approach, I would go over the other routines (testing etc.), too.

**Checklist**

- [X] The documentation has been updated.
- [ ] If the PR solves a specific issue, it is set to be closed on merge.

### CODE REVIEW

**Comment by weslleyspereira** [comment]
Great PR! Thanks a lot for working on that.

I think we have at least 3 other people in favor of removing LABAD from LAPACK. Please, see https://github.com/Reference-LAPACK/lapack/discussions/727.

**Review by langou — DISMISSED** [review]

**Comment by martin-frbg** [comment]
How about adding a (non-fatal !) build-time test just in case there is something more modern around than a late-1990s Cray with the same limitations ?

**Comment by langou** [comment]
Thanks @martin-frbg. 

I think I understand what you are saying but (1) I do not think LABAD translate to any modern architecture, and ever will, (2) it was a dirty fix back then, it is still a dirty fix and we should remove this, if we want to do this again, we should do something differently.


The way I am reading LABAD is as follows. 

(1) We can only use half of the range of numbers with confidence on old Cray's machine. So we want to restrict the range on an old Cray's by doing something like:
https://github.com/Reference-LAPACK/lapack/blob/cfaa5aefabb0dc3292c9c355d17c228f6351d7d8/SRC/dlabad.f#L94-L95

(2) How do we know we are on an old Cray? They have a huge range of number, LARGE is greater than +10^2000, so we can know we are on an old Cray by checking LARGE:
https://github.com/Reference-LAPACK/lapack/blob/cfaa5aefabb0dc3292c9c355d17c228f6351d7d8/SRC/dlabad.f#L93

The whole thing feels bogus to me. This is nice historical piece of software but I think we can safely move on from this routine.

Julien.

**Comment by angsch** [comment]
LABAD is now fully removed from the numerical functions and tests; LABAD itself is no-op.

I intentionally did not move LABAD to the deprecated folder. This is to avoid an undefined symbol if someone calls LABAD in a custom external legacy routine. Recall that the deprecated routines are not built by default.

**Review by langou — APPROVED** [review]

**Pull request merged**
