### PR TITLE
fix dlanv2 and slanv2

### PR DESCRIPTION
**Pull request by thijssteel**
My attempt at fixing #263

The problem was underflow (and it's probably also weak to overflow), so the fix is simply to scale the relevant parts in a similar way to XLARTG.

I've also gone ahead and included the changes suggested by Martin so we don't get an infinite loop in case of Inf or Nan.

### CODE REVIEW

**Comment by thijssteel** [comment]
this is going to need some more testing before merging, those coverage changes seem pretty suspicious

**Comment by martin-frbg** [comment]
Still unsure what to make of codecov reports even after thomasrockhu's explanation in #444 - maybe this is still an artefact of just having restored the travis runs (which contain coverage builds as well) yesterday ?

**Comment by thijssteel** [comment]
oh, #444 does explain a lot, I've been going crazy trying to find the cause.

**Comment by martin-frbg** [comment]
LGTM, thanks

**Pull request merged**
