### PR TITLE
Tsqr

### PR DESCRIPTION
**Pull request by sydha**
Tall skinny and short wide routines added.

### CODE REVIEW

**Comment by langou** [comment]
Thanks Syd. We will have a look. Julien.

**Comment by zerothi** [comment]
May I come with a few comments:

1) the .DS_store file should be removed from the revisions
2) The *_aasen routines have been removed from the Makefile, however, they should remain, no?
3) It seems like the ilaenv has been copied from a previous revision (i.e. no merging), version numbers etc. have changed to previous values, also particularly the 'ESV' check is removed in this revision.

**Comment by julielangou** [comment]
I did not look at the code yet, but CMake Makefile needs to be modified too.

**Comment by julielangou** [comment]
I did not look at the code yet, but CMake Makefile needs to be modified too. 
Since Travis is using the CMake Build, tests are failing too.

**Pull request merged**
