### PR TITLE
remove redundant space from xerbla call sbgv/hbgv

### PR DESCRIPTION
**Pull request by dklyuchinskiy**
Part of issue #791.

### CODE REVIEW

**Review by langou — APPROVED** [review]

**Comment by langou** [comment]
Thanks. I do not have a strong opinion about these white spaces. Either way is fine. Thanks for the PR. That's great.

**Comment by dklyuchinskiy** [comment]
> Thanks. I do not have a strong opinion about these white spaces. Either way is fine. Thanks for the PR. That's great.

I just wrote a small unit test to see the error message, which xerbla returns, and it is failed due to additional space in naming. Now behaviour is alinged with other LAPACK functions.

Thanks for the merge!

**Comment by langou** [comment]
Ah! OK. Thanks for letting me know. Perfect then.

**Comment by martin-frbg** [comment]
Actually many (most?) five-letter functions that use XERBLA have this trailing space, maybe it is the unit test that needs to be more flexible ?

**Comment by dklyuchinskiy** [comment]
> Actually many (most?) five-letter functions that use XERBLA have this trailing space, maybe it is the unit test that needs to be more flexible ?

OMG, indeed. I did not check other 5 letter functions... Is it done for special purpose? LAPACK namings can be more than 6 letters.

Yeap, unit test can be changed, but it should be? Unfortunately, trailing space led to misundersanding from my side. It could be reverted if there exists LAPACK standard in such case. But for my point of few it is not aligned between functions.

**Comment by langou** [comment]
> Is it done for special purpose? 

No, this is a remnant of FORTRAN 77. Six-letter is not needed any longer. The space in the parameter passed to XERBLA is not needed any longer.

The code with a space `CHBGV ` is OK. The code without a space is OK too.  I am fine either way. 

XERBLA should work with a space in the name of the subroutine. So it does bother me that the code with a space is a problem on your end. That being said, we can remove the space. I do not mind.

LAPACK namings can be more than 6 letters.

I agree with @martin-frbg that we want to be consistent across 5-letter-name subroutines.

**Comment by dklyuchinskiy** [comment]
@langou thank you for comprehensive explanation!

Of course, it would be nice to have the same style for all 5-letter-name subroutines. Indeed, not all are aligned. For example, `GEQR`, `GELQ`, and now `SBGV` :sweat_smile: If it is not a big problem at the moment, it can be kept as is.

**Pull request merged**
