### PR TITLE
Multishift QZ with AED

### PR DESCRIPTION
**Pull request by thijssteel**
(PR reopened because I had to change branches)

This PR adds an implementation of the multishift QZ algorithm with AED.
It is loosely based on my implementation of the rational QZ algorithm (https://github.com/thijssteel/multishift-multipole-rqz).

It features:
- Agressive early deflation
- Multishift QZ sweeps using optimal packing of the bulges
- A new heuristic to select the number of positions in the sweep windows

It does not feature:
- A windowed deflation of infinite eigenvalues (that is only useful if many infinite eigenvalues are to be deflated and in that case you should probably do some preprocessing anyway).

All things considered this won't significantly reduce the runtime of generalised schur form calculations because the HT reduction is now dominant, but I hope be able to have a really fast implementation of that soon.

depends on #420

### CODE REVIEW

**Comment by thijssteel** [comment]
Two updates:

- I've decided to use the same parameters as for the QR algorithm. This is a bit cleaner, but because of optimal packing, that is suboptimal.

- I mentioned that the HT reduction is now dominant. That was slightly wrong because I was linking with the MKL version of LAPACK and they disable the blocked HT reduction for some reason. A proper implementation is already much faster.

This implementation should be done now, let me know if you need anything else like documentation or performance tests.

**Comment by thijssteel** [comment]
I've done some performance tests on my laptop. The following table shows execution time in seconds for different pencil sizes.

| N    | DLAQZ0 (easy pencil) | DLAQZ0 (hard pencil) | DHGEQZ (easy pencil) | DHGEQZ (hard pencil) |
|------|----------------------|----------------------|----------------------|----------------------|
| 1000 | 1.2477440            | 1.8427166            | 4.4717226            | 5.2714647            |
| 1414 | 1.8305675            | 3.4307614            | 13.5002084           | 15.8388140           |
| 2000 | 3.2328878            | 6.4804934            | 41.9715897           | 49.1257091           |
| 2828 | 3.9365313            | 15.0546696           | 118.7894478          | 135.7473488          |
| 4000 | 8.8735433            | 31.2473274           | 365.1408321          | 400.7008308          |

**Comment by langou** [comment]
40x speedup!!!!

**Comment by thijssteel** [comment]
Yeah, pretty massive speedup. It's the result of years of research culminating in one implementation (because DHGEQZ is quite old). Compared to more recent libraries like NLAFET this is only about twice as fast though.

**Comment by weslleyspereira** [comment]
Hi @thijssteel . I want to review your PR, but I think we need to rebase it first. There are some conflicts with the `xLAQZ#` methods. I think that was caused by the final version of #420. Should I merge accepting the master version for the conflicts?

**Comment by thijssteel** [comment]
Wait, there ar conflicts in xLAQZ#? But master doesn't contain those routine, they are new with this PR.

**Comment by thijssteel** [comment]
image
my github says this, sure its not a local issue?

**Comment by weslleyspereira** [comment]
Sorry... local issue here. I had an older version of your branch. Thank you!

**Comment by weslleyspereira** [comment]
`ctest` reports `100% tests passed, 0 tests failed out of 103`. However, `Testing/Temporary/LastTest.log` had

```
			-->   LAPACK TESTING SUMMARY  <--
		Processing LAPACK Testing output found in the TESTING directory
SUMMARY             	nb test run 	numerical error   	other error  
================   	===========	=================	================  
REAL             	1316145		0	(0.000%)	0	(0.000%)	
DOUBLE PRECISION	1315875		1	(0.000%)	0	(0.000%)	
COMPLEX          	776316		0	(0.000%)	0	(0.000%)	
COMPLEX16         	777128		0	(0.000%)	0	(0.000%)	

--> ALL PRECISIONS	4185464		1	(0.000%)	0	(0.000%)
```

Inside `dgd.out` I found:

```
 -----------------------------------------------------------------------

 Tests of the Generalized Nonsymmetric Eigenvalue Problem Driver DGGEV

 LAPACK VERSION 3.9.0

 The following parameter values will be used:
    M:         2     6     8    10    15    20
    N:         2     6     8    10    15    20
    NB:        1
    NBMIN:     1
    NX:        1
    NS:        2
    MAXB:      1

 Relative machine underflow is taken to be    0.222507-307
 Relative machine overflow  is taken to be    0.179769+309
 Relative machine precision is taken to be    0.111022D-15

 Routines pass computational tests if test ratio is less than   10.00


 DGV routines passed the tests of the error exits (108 tests done)

 All tests for DGV drivers  passed the threshold (   1092 tests run)

 DGV -- Real Generalized eigenvalue problem driver
 Matrix types (see DDRGEV3 for details): 
 Special Matrices:                       (J'=transposed Jordan block)
   1=(0,0)  2=(I,0)  3=(0,I)  4=(I,I)  5=(J',J')  6=(diag(J',I), diag(I,J'))
 Diagonal Matrices:  ( D=diag(0,1,2,...) )
   7=(D,I)   9=(large*D, small*I)  11=(large*I, small*D)  13=(large*D, large*I)
   8=(I,D)  10=(small*D, large*I)  12=(small*I, large*D)  14=(small*D, small*I)
  15=(D, reversed D)
 Matrices Rotated by Random Orthogonal Matrices U, V:
  16=Transposed Jordan Blocks             19=geometric alpha, beta=0,1
  17=arithm. alpha&beta                   20=arithmetic alpha, beta=0,1
  18=clustered alpha, beta=0,1            21=random alpha, beta=0,1
 Large & Small Matrices:
  22=(large, small)   23=(small,large)    24=(small,small)    25=(large,large)
  26=random O(1) matrices.

 Tests performed:    
 1 = max | ( b A - a B )'*l | / const.,
 2 = | |VR(i)| - 1 | / ulp,
 3 = max | ( b A - a B )*r | / const.
 4 = | |VL(i)| - 1 | / ulp,
 5 = 0 if W same no matter if r or l computed,
 6 = 0 if l same no matter if l computed,
 7 = 0 if r same no matter if r computed,

 Matrix order=   20, type=22, seed=1749, 469,1744,2797, result  5 is 4.504D+15
 DGV drivers:      1 out of   1092 tests failed to pass the threshold

 -----------------------------------------------------------------------
```

One of your random upper Hessenberg pencils with singular B is failing. I removed the new tests you proposed in `ddrgev3.f`and the failing test disappeared. Could please verify you obtain the same behavior there? Thanks!

**Comment by thijssteel** [comment]
i obtain the same behavior. I'll investigate the cause.

**Comment by thijssteel** [comment]
found the problem:

It's caused by a convergence failure. Then DHGEQZ takes over, but because that uses the norm of A and B, it can differ slightly when not updating those matrices fully.

The root of the problem appears to be the shift selection. The shifts should be sorted in DLAQZ0 so that when some shifts are dropped, we don't split a double shift. I'll make a fix soon.

**Comment by weslleyspereira** [comment]
Now all tests pass, thanks!

Now everything is good to me :)

**Comment by langou** [comment]
Hi @thijssteel, why are you modifying HGEQZ in this PR? I did not have time to fully review the change on HGEQZ, but I think we already accepted these changes in another PR, did not we? @langou

**Comment by langou** [comment]
I was reviewing the PR. This is great to me. 

Related some, but not of consequence for this PR. This reminds me that we need to push GGHD3() to GGEV().

GGHD3() is the blocked version of GGHRD(). When we released GGHD3(), we created GGES3() as a driver that calls GGHD3(). GGES3() is meant to replace GGES(). GGES() was calling GGHRD(). 

That being said a similar change was never done to GGEV(). 

Maybe I will create an issue, and we can have this as a TODO / wishlist, and someone can pick this action item up. 

The action item will be to create GGEV3() that (1) calls GGHD3() instead of GGHRD() and (2) calls LAQZ0 instead of HGEQZ(). 

Let me know if this does not make sense.

**Comment by thijssteel** [comment]
@langou those changes to HGEQZ modify the deflation criterium. It now deflates by comparing to the diagonal elements adjacent to the element, similar to the QR algorithm (although i didn't implement the stricter checks by tissuer).

**Comment by weslleyspereira** [comment]
Hi @thijssteel. I was checking the tests in this branch and found failures generated by `CLAQZ0` and `ZLAQZ0`. The failure didn't appear in the summary of tests using `ctest`, that is why I haven't noticed it before.

1. How to reproduce the failures:

```sh
bin/xeigtstc < ../TESTING/cgd.in # or
bin/xeigtstz < ../TESTING/zgd.in
```

Although they seem to be related to `CTGSYL` and `ZTGSYL`, they aren't. You can see it using via debug.

2. The failures weren't there before my commits, since the failures are related to the call inside the xGGEV subroutines. Also, when we replace `CLAQZ0` by `CHGEQZ` or, `ZLAQZ0` by `ZHGEQZ`, the failures disappear.

3. I know where the problem is!
    - The program calls `xLAQZ0`.
    - `xLAQZ0` calls `xLAQZ2` with `NW=0` (I think there is a problem here).
    - Then `xLAQZ2` calls `xLAQZ0` with `N=0, ILO=1` and `IHI=0`.
    
Can you check this? :)

**Comment by weslleyspereira** [comment]
An additional comment: Travis printed out the error messages but the tests all pass... Strange behavior.

**Comment by thijssteel** [comment]
I'll make some time to look at it in the weekend, but NW=0 should not be possible.

The only thing i can think of is that NWR is not set in ILAENV in that particular test. Do you still know what specific test failed?

**Comment by thijssteel** [comment]
Note to self: possible related to the XGGEV routines

**Comment by weslleyspereira** [comment]
> I'll make some time to look at it in the weekend, but NW=0 should not be possible.
> 
> The only thing i can think of is that NWR is not set in ILAENV in that particular test. Do you still know what specific test failed?

Yes. That's exactly it. ILAENV returns 0 for this test. The first test in `cgd.in` and `zgd.in` fail. Not only the first, but you can look at the first.

**Comment by thijssteel** [comment]
Is it the responsibility of the routine to check if ilaenv is valid?

**Comment by thijssteel** [comment]
should be solved now

**Comment by weslleyspereira** [comment]
Thanks! You're the best! Now I saw how we need to set the parameters in the specific "err" files.

Just for my personal record:
- Out of the test suite: `ILAENV(ISPEC=12,...,17)` calls `IPARMQ(ISPEC)`
- Inside the test suite: `ILAENV(ISPEC=12,...,17)` access the array `IPARMS(ISPEC)`

**Comment by thijssteel** [comment]
Perhaps it would be a good idea to initialize that array to the values in IPARMQ to avoid issues with it in the future.

**Comment by weslleyspereira** [comment]
Probably.. The problem is that we have different values being set for the same `ISPEC`. See:

https://github.com/thijssteel/lapack/blob/0b8015ebeb342abeaa2dcf8d350c0223ad2e80ed/TESTING/EIG/cchkee.f#L1248

https://github.com/thijssteel/lapack/blob/0b8015ebeb342abeaa2dcf8d350c0223ad2e80ed/TESTING/EIG/cchkee.f#L1387

https://github.com/thijssteel/lapack/blob/0b8015ebeb342abeaa2dcf8d350c0223ad2e80ed/TESTING/EIG/cchkee.f#L1808

**Comment by langou** [comment]
> I've done some performance tests on my laptop. The following table shows execution time in seconds for different pencil sizes.
> 
> N	DLAQZ0 (easy pencil)	DLAQZ0 (hard pencil)	DHGEQZ (easy pencil)	DHGEQZ (hard pencil)
> 1000	1.2477440	1.8427166	4.4717226	5.2714647
> 1414	1.8305675	3.4307614	13.5002084	15.8388140
> 2000	3.2328878	6.4804934	41.9715897	49.1257091
> 2828	3.9365313	15.0546696	118.7894478	135.7473488
> 4000	8.8735433	31.2473274	365.1408321	400.7008308

Hi Thijs, what is an easy pencil? And what is a hard pencil? I am trying to time this as well. Julien.

**Comment by thijssteel** [comment]
These pencils are also discussed in the paper (and in other papers for that matter).

The easy pencil is generated in Hessenberg upper triangular form with randomly drawn entries. The hard pencil is the same but with entries A_ij = i + j and B_ij = 3i + 2j.

You may need to adapt the parameters to achieve optimal speedup.

I'll dig up the test code later for you.

**Comment by thijssteel** [comment]
@langou this is the code i used for testing: https://gist.github.com/thijssteel/6b2b7509fdc0a86fed5cc925ca268963

it should be linked with mmio.f for matrix market files.

Command line arguments:

- Algorithm: 1 for DLAQZ0, 2 for DHGEQZ
- Matrixtype: 1 for random, 2 for i+j, 3 for matrix market
- N/File: when matrixtype is 1 or 2, an integer denoting the size of the pencil, when matrixtype is 3, two filenames of matrix market files

**Comment by langou** [comment]
Thanks for sharing @thijssteel ! This is helpful! Cheers, Julien.

**Comment by weslleyspereira** [comment]
Hi! I've just reverted my commits related to the GGEV subroutines. We (@langou and I) recently realized we actually needed to test GGEV3. Sorry for this confusion.

**Comment by langou** [comment]
To report a good news. MathWorks took the QZ code from Thijs to be released in 3.10, and they used it in their test suite, and the QZ code passes their test suite. So this is really great! Big thanks to MathWorks for taking the time to export the pre-release of LAPACK 3.10, compile it, sneak it under the hood of Matlab, and run their test suite. Everything is running fine. So thanks to MathWorks, and thanks to Thijs.

**Comment by weslleyspereira** [comment]
> I've done some performance tests on my laptop. The following table shows execution time in seconds for different pencil sizes.
> N 	DLAQZ0 (easy pencil) 	DLAQZ0 (hard pencil) 	DHGEQZ (easy pencil) 	DHGEQZ (hard pencil)
> 1000 	1.2477440 	1.8427166 	4.4717226 	5.2714647
> 1414 	1.8305675 	3.4307614 	13.5002084 	15.8388140
> 2000 	3.2328878 	6.4804934 	41.9715897 	49.1257091
> 2828 	3.9365313 	15.0546696 	118.7894478 	135.7473488
> 4000 	8.8735433 	31.2473274 	365.1408321 	400.7008308

Hi @thijssteel. What kind of BLAS did you use to obtain these results? And what was your processor? Thanks.

**Comment by thijssteel** [comment]
Intel MKL (can't remember the version, but probably doesn't matter that much). Machine has an Intel Xeon E5-2697 v3 CPU with
14 cores and 128GB of RAM. The parameters were also adapted to achieve this performance (see a commit in the tree i reverted)

**Comment by weslleyspereira** [comment]
I did some experiments on my laptop too. My objective was to run this branch without optimizing the parameters.

For that I used:
- @thijssteel's code: https://gist.github.com/thijssteel/6b2b7509fdc0a86fed5cc925ca268963.
- `mmio.f` from https://math.nist.gov/MatrixMarket/mmio/f/mmio.f.
- OpenBLAS (https://github.com/xianyi/OpenBLAS/tree/f9aaf22fc3aa63fd74c0f268826235a65d12cf4c) build with `cmake -DCMAKE_BUILD_TYPE=Release`. No additional configuration.
- This branch (#421) build with `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_Fortran_FLAGS=-fopenmp`

My system:
- Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
- 7.8 GB RAM
- Ubuntu 18.04.5 LTS (5.4.0-70-generic)
- GNU compilers, GCC version 7.5.0

Results:
| N    | DLAQZ0 (easy pencil) | DLAQZ0 (hard pencil) | DHGEQZ (easy pencil) | DHGEQZ (hard pencil) |
|------|----------------------|----------------------|----------------------|----------------------|
| 1000 | 1.5187637            | 2.5955450            | 6.8730151            | 6.6085497            |
| 2000 | 4.3298647            | 9.8546768            | 54.9083396           | 55.6486221           |
| 3000 | 19.8760378            | 35.1632956            | 198.6228615           | 194.1338587           |
| 4000 | **34.8435903**            | 88.3386668           | **439.0105713**          | 484.1612056          |
* All the results represent the best time in 3 runs.

We still arrive at 12x speedup, and that is awesome!!

**Comment by langou** [comment]
Interesting comparison. My take away is that @thijssteel's laptop is faster than @weslleyspereira's laptop ;)


( More seriously, thanks for the timing @weslleyspereira, it's great. )

**Comment by thijssteel** [comment]
I want to note that the original 40× speedup is somewhat unrealistic. With well tuned parameters, that easy pencil just keeps doing aed and no sweeps are required. I reverted that commit because i don't want to optimise for such a special case.

**Comment by weslleyspereira** [comment]
At the request of @langou, I did some additional experiments for the GGES3 on my laptop.

- Adaptation to @thijssteel's code: https://gist.github.com/weslleyspereira/15929a3a363683ddac5647ee2fe73723.
- OpenBLAS (https://github.com/xianyi/OpenBLAS/tree/f9aaf22fc3aa63fd74c0f268826235a65d12cf4c) build with `cmake -DCMAKE_BUILD_TYPE=Release`. No additional configuration.
- weslleyspereira/LAPACK branches:
  - DGGES3 using DGGHD3 and DLAQZ0: https://github.com/weslleyspereira/lapack/tree/multishift-aed-QZ-performance
  - DGGES3 using DGGHRD and DHGEQZ: https://github.com/weslleyspereira/lapack/tree/no-multishift-aed-QZ-performance
- general matrices with random numbers, `USER_SEED = 1` 

My system:
- Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz **(12 cores)**
- 7.8 GB RAM
- Ubuntu 18.04.5 LTS (5.4.0-70-generic)
- GNU compilers, GCC version 7.5.0

Results (best time of 3 runs of `DGGES3`):

| N    | DGGES3      | DGGHD3              | DLAQZ0             |
|------|-------------|---------------------|--------------------|
| 1000 | 3.1482918   | 1.7105347   (54.3%) | 1.3828994  (43.9%) |
| 2000 | 17.7040713  | 12.8302498  (72.5%) | 4.3809202  (24.7%) |
| 3000 | 69.7460524  | 46.6079671  (66.8%) | 10.2170884 (14.6%) |
| 4000 | 145.9439852 | 119.7468701 (82.0%) | 17.1359081 (11.7%) |

| N    | DGGES3      | DGGHRD              | DHGEQZ              |
|------|-------------|---------------------|---------------------|
| 1000 | 5.3760809   | 2.0468199   (38.1%) | 3.2798471   (61.0%) |
| 2000 | 57.9165448  | 27.2491951  (47.0%) | 30.0143812  (51.8%) |
| 3000 | 215.3769933 | 108.1476715 (50.2%) | 105.4639979 (49.0%) |
| 4000 | 537.6017731 | 291.7817445 (54.3%) | 241.6236139 (44.9%) |

**Comment by langou** [comment]
Thanks for the run @weslleyspereira !

GEES3 parameters for this experiment are: JOBVSL = ’N’, JOBVSR = ’N’, SORT = ’N’.

So in short, taking N=4,000 as a reference,  GGES3 is 3.7x faster in v3.10 than v3.5.

This is because GGHD3 (released in v3.6, Nov 2015) is 2.4x faster than GGHRD (in v3.5).

And then LAQZ0 (will be released in v3.10, June 2021) is 14.1x faster than HGEQZ (in v3.9).

In v3.5, the times in GGHRD and HGEQZ were about 54.3% and 44.9% resp. of GGES3.

In v3.10, the times in GGHRD and HGEQZ are about 82.0% and 11.7% resp. of GGES3.

So, now that QZ is so fast, the reduction to Triangular Hessenberg has become the major bottleneck of GGES3. 

All these experiments are done without any tuning and using the default parameters.

**Comment by weslleyspereira** [comment]
Yes. That's it! I should also say that DLAQZ0 uses all my cores during almost all its execution. But we may need to use a proper profiler to get more information about core occupancy and balancing.

**Comment by thijssteel** [comment]
I don't think OpenBLAS can utilize a variable amount of cores. Its just a switch between threading and not threading. Using MKL reveals that it doesn't scale all that well (up to about 4 cores). Most of the multiplications involve thin matrices (This may improve with other parameters).

**Review by langou — APPROVED** [review]

**Pull request merged**
