### PR TITLE
style: Fix typo in docstrings

### PR DESCRIPTION
**Pull request by jcfr**
Issues were identified using the open-source tool codespell [1]
running the following command from the source directory:

[1] https://github.com/codespell-project/codespell#readme

```
$ codespell -q6 \
  --skip=".git,Doxyfile,Doxyfile_man,CMakeLists.txt,Makefile" \
  --regex="\w[a-z\-\_]+" \
  --ignore-words-list="fro,ith,nd,noe,numer" \
  --summary

[...]

-------8<-------
SUMMARY:
acoording     2
agressive     8
ajust        12
arithmetics   5
comleted      2
contraints    8
equaly        4
everytime     4
febuary       1
matix         8
otherwize     4
overwrittes   4
owerflow      8
parmeter      4
permutaions  32
specturm      8
```

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @julielangou

**Comment by langou** [comment]
Oh my this codespell software is awesome! I am giving it a star right now on GitHub :). Thanks Jean-Christophe. This helps! Cheers, Julien.

**Comment by julielangou** [comment]
indeed, did not even know it was existing...

**Comment by jcfr** [comment]
It is quite nice. 

The only down side is that the use of `--regex` is not compatible with the parameter `--write-changes`, this means I add to to replace words myself ... but finding the issues was already great.

Using `--regex` was required to ignore upper case words, otherwise I was getting a lot of false positive.

An other approach would be to provide a dictionary of word to exclude ...

**Pull request merged**
