### PR TITLE
Update conda version used in Appveyor

### PR DESCRIPTION
**Pull request by martin-frbg**
**Description**
fixes recent CI failures with internal conda errors like  "InvalidVersionSpecError: Invalid version spec =2.7" (see also conda/conda issue 10618) and inability to install the "charset-normalizer" package
**Checklist**
N/A

### CODE REVIEW

**Review by weslleyspereira — APPROVED** [review]
Hi @martin-frbg, thanks for the PR!

I observed another problem with recent runs of AppVeyor, e.g., https://ci.appveyor.com/project/langou/lapack/builds/41852332
Do you know if this PR also fix that behavior?

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::charset-normalizer-2.0.9-pyhd8ed1ab_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda36-x64\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
Rolling back transaction: ...working... done
CondaError: Cannot link a source that does not exist. C:\Miniconda36-x64\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
if (-Not (Test-Path .\build)) { mkdir build }
cd build
cmake -G "NMake Makefiles JOM" -DCMAKE_Fortran_COMPILER=flang -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_Fortran_COMPILER:
    C:/Miniconda36-x64/Library/bin/flang.exe
  is not a full path to an existing compiler tool.
  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
-- Configuring incomplete, errors occurred!
See also "C:/projects/lapack/build/CMakeFiles/CMakeOutput.log".
See also "C:/projects/lapack/build/CMakeFiles/CMakeError.log".
Command exited with code 1
```

**Comment by martin-frbg** [comment]
I don't know, but closing and reopening this PR (to rerun the CI) should tell

**Comment by weslleyspereira** [comment]
Same problem. Thanks for rerunning it.

**Comment by martin-frbg** [comment]
nope, seems to be a more recent problem. (the only reference I can find is from Oct 15, but only a githubmemory link with no accessible primary source)

**Comment by weslleyspereira** [comment]
Hi @martin-frbg. Do you have any update on this thread? The current script for Appveyor is not working.

**Comment by martin-frbg** [comment]
I had pretty much given up on this - no time and energy to debug conda on top of everything else. The originally proposed fix used to work for a few weeks around when I created the PR... The appveyor.yml in OpenBLAS does not have this problem, but the difference in base images may explain that.

**Comment by martin-frbg** [comment]
I guess we may want to keep the one commented line that disabled automatic updates of conda itself. The others are either options I moved into the remaining commands, or commands that did nothing to solve the problem. (And I notice that the title of this PR is outdated now as well)

**Comment by langou** [comment]
Thanks @martin-frbg for getting appveyor to work again!

**Review by weslleyspereira — APPROVED** [review]
Thanks for the effort dedicated to this PR!

**Comment by martin-frbg** [comment]
We'll probably need a follow-on to reenable the build cache once this is merged (and Appveyor has run once more)

**Comment by weslleyspereira** [comment]
> We'll probably need a follow-on to reenable the build cache once this is merged (and Appveyor has run once more)

Ok! I will merge it now, and we watch how it behaves. Thanks!

**Pull request merged**
