### PR TITLE
fix redundant install of cblas_test.h

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

---

I'm hoping to fix the names of the header files, so that standard 32bit and extended 64 bit can be installed simultaneously.
This is a small step towards that, shouldn't have any regressions.
All tests are passing.

### CODE REVIEW

**Comment by weslleyspereira** [comment]
Hi @epsilon-0. Thanks for work on this fix! Do you know if the Makefile version needs any updates too? I am planning to soon propose a PR that adds Makefile on Travis CI.

**Comment by epsilon-0** [comment]
I am unsure, I haven't used the Makefile version.
I can take a look tonight.

**Comment by weslleyspereira** [comment]
Thanks! :)

**Comment by weslleyspereira** [comment]
> Hi @epsilon-0. Thanks for work on this fix! Do you know if the Makefile version needs any updates too? I am planning to soon propose a PR that adds Makefile on Travis CI.

I made it! Look at #500. Also, PR #507 has included some new targets on Travis CI, and #508 is doing the same.

**Review by weslleyspereira — APPROVED** [review]

**Review by langou — APPROVED** [review]

**Pull request merged**
