### PR TITLE
fix #467

### LINKED ISSUE #467: Wrong declaration of CDUM in c/zgesdd
In c/zgesdd.f line 276 CDUM(1) is declared.
This is wrong because CDUM(4) is referenced in c/zungbr.f line 234 as A(2,2).

I suggest declaring CDUM(LDA*N) to avoid undefined behaviour.

### PR DESCRIPTION
**Pull request by langou**
Fix issue "Wrong declaration of CDUM in c/zgesdd" #467 from @vzecca by
passing A(1,1) instead of A(2,2) on lines 225 and 234 of SRC/[c/z]ungbr.f

### CODE REVIEW

**Comment by zerothi** [comment]
While this fixes the issue, I think the intent of the original implementation was that the array passed to those calls (`[cz]ungbr`) are sub-matrices.  
To retain that I would argue they shouldn't be changed, but I don't know if this is a violation?

The calls are still doing work-size queries, so I think we should pass `A` instead of `CDUM`?

**Comment by langou** [comment]
Hi Nick. I think passing A in [C/Z]GESDD (when calling [C/Z]UNGBR  during the workspace query at line 356) would result in the same problem as passing CDUM. Indeed when the user calls [C/Z]GESDD for a workspace query, even if M>1, and N>1, I do not think we can expect the array A to have A(2,2) correctly allocated. Most users probably call with a "correct" A. But, for example, in this case, the user "C/Z]GESDD" calls [C/Z]UNGBR with CDUM(2,2) not correctly allocated, and I think, this is a correct usage during workspace query. So, all this to say, that I do not think passing A in [C/Z]GESDD would be a better fix. Cheers, Julien.

**Comment by martin-frbg** [comment]
So what is/was wrong with my suggestion to correct the dimensioning of CDUM in the test driver and leave everything unchanged ?
A mere workspace query will not access the elements in any case.

**Comment by langou** [comment]
to @martin-frbg: (1) I did not understand you made this suggestion, sorry, I did not understand anyone made this suggestion, (2)  yes, declaring CDUM(2,2) in [C/Z]GESDD would also do the trick. I agree. (3) I prefer to use CDUM(1) in the workspace query of [C/Z]UNGBR (which is what the PR does). 

This is a matter of preference. I do not have a strong opinion on this. So if someone has a strong opinion one way or another, I am happy to go either way.

I think we should not have [C/Z]UNGBR make a call using A(2,2) or CDUM(2,2) if this does not exist, even in a workspace query. So I think we should fix this one way or another. This is not critical. But it would be better, in my opinion, if this is fixed.

**Comment by martin-frbg** [comment]
Ah right, sorry, I confused this with the earlier issue #145 that also got mentioned in #467 (and for which I already committed my supposed fix). I agree that the only "advantage" in keeping the (2,2) argument would be to make the function call look the same for workspace query and the actual computation. (Wonder if the argument should then be passed as simply "A" like in the other branch of the conditional ?)

**Comment by langou** [comment]
You mean, instead of changing `A(2,2)` to `A(1,1)` in this PR, change `A(2,2)` to `A`. I see. Yes. Indeed. This could be nicer.

**Review by thijssteel — APPROVED** [review]

**Review by weslleyspereira — APPROVED** [review]

**Comment by weslleyspereira** [comment]
Hi! I think all agree the changes @langou proposed are sufficient to solve the bug. So, I've just accepted it. :)

**Pull request merged**
