### PR TITLE
Add forgotten API_SUFFIX wrappers to LAPACKE_?TFSM and fix the MacOS CI jobs

### PR DESCRIPTION
**Pull request by martin-frbg**
**Description**
The missing API_SUFFIX wrappers appear to be an oversight from the recent #1042
This version of the PR combines my previous #1046 with my unrelated PR #1045 to
fix the CI jobs that got broken by the removal of gcc-11 from the underlying image
(as requested by @weslleyspereira)

### CODE REVIEW

**Review by langou — DISMISSED** [review]

**Review by langou — DISMISSED** [review]

**Review by weslleyspereira — DISMISSED** [review]
Thanks! Looks good to me and the CI is happy.

**Comment by martin-frbg** [comment]
(and obviously it is not me dismissing your reviews, but github hiccuping due to that "partial" merge)

**Comment by langou** [comment]
Let us revert my previous merge #1046. And start clean.

**Comment by martin-frbg** [comment]
Idk, the two PRs are technically unrelated (which is why I had them separate originally) and this here is exactly identical content-wise. So IMHO reverting just to get this one in would be messier ?

**Review by weslleyspereira — DISMISSED** [review]

**Review by langou — APPROVED** [review]

**Review by langou — APPROVED** [review]

**Comment by weslleyspereira** [comment]
> Idk, the two PRs are technically unrelated (which is why I had them separate originally) and this here is exactly identical content-wise. So IMHO reverting just to get this one in would be messier ?

You were right about the mess.

We ended up merging #1045 and #1046, so we can close this one without merge. Sorry for the trouble!

**Pull request closed without merging**
